## Config for extra markdown features
goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    autoHeadingID: true
    autoHeadingIDType: 'github'
    attribute:
      block: true
      title: true
      table: true
  renderer:
    unsafe: true
    