Title: Identifying Nelson/Buscando a Roberto
description: "An upcoming documentary film by Nelson/Roberto and John Younger about El Salvador's Disappeared Children."
keywords: "Documentary, Film, El Salvador, Disappeared, Children, Nelson/Roberto"
copyright: "[Cabin 23 Productions](https://cabin23productions.com/)"
images: 
  - images/identifying_nelson_buscando_a_roberto_poster_preview.png
themeColor: 
  - schema: light
    content: "#51462c"

socialLinks:
  - url: https://www.instagram.com/inbarfilm/
    icon: brands fa-instagram
    label: Instagram
  - url: https://www.youtube.com/@inbarfilm
    icon: brands fa-youtube
    label: YouTube
  - url: "mailto:info@identifyingnelson.com"
    icon: solid fa-envelope
    label: Email