en:
  languageName: "English"
  contentDir: content/en
  baseURL: https://www.identifyingnelson.com/
es:
  languageName: "Español"
  contentDir: content/es
  baseURL: https://www.buscandoaroberto.com/